spring:
  profiles:
    active: dev

  ## .sql문을 실행하기 위함
  sql:
    init:
      mode: always

  ## hibernate ddl 이후 datasource intialize
  jpa:
    defer-datasource-initialization: true


springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true  # 요청 실행 시간 표시
    # groups-order: DESC
    operationsSorter: method  # CRUD 메소드 순으로 정렬
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
#  group-configs:
#    - group: stores
#      paths-to-match: /store/**
