social:
  kakao:
    accessToken: ii-Xj09q6eckCENMFLYSgcii7848mixM0CUKKcjYAAABi3GvfeXOkqTnJF629A
    client-id: afe2e06e75ffbbcc136475a5cf4b7efc
    redirect: /oauth/kakao/redirect
    url:
      login: https://kauth.kakao.com/oauth/authorize
      token: https://kauth.kakao.com/oauth/token
      profile: https://kapi.kakao.com/v2/user/me
      unlink: https://kapi.kakao.com/v1/user/unlink
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      hbm2ddl.auto: update
      format_sql: true
    show-sql: true
    generate-ddl: true
    open-in-view: false
  messages:
    basename: i18n/exception
    encoding: UTF-8
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    driver-class-name: org.h2.Driver
    username: sa
  url:
    base: http://localhost:8080
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
